<a href="https://colab.research.google.com/github/NeelkanthMehta/hello-world/blob/master/TS_Simplilearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to TensorFlow
### Overview
Originally developed to run large numerical computations, it is an opensource library developed by Google.

Has a faster compilatioin time than other Deep Learning libraries like Keras and PyTorch.

Supports both CPUs and GPUs.

Accepts data in the form of multidimentional arrays of higher dimensions called Tensors

Works on basis of data flow graphs that have nodes and edges, making it easier for parallel processing.

**What is a Tensor?**

A Tensor is a generalizatioin of vectors and matrices of potentially higher dimensions. Arrays of data w/ different dimensions and rank that are fed as input to the neural network

**Dimension**: Tensor of Rank 0, 1, 2, 3

Each computation in TF is represented as a data flow graph - Each node in the grpah represents a mathematical operation (add, subtract, multiply, etc.) and each edge represents multidimensional arrays (Tensors) - Computational graph is the graph of programming logic which TF builds in the memory - enables creating large neural networks as computing can be distributed across several CPUs or GPUs

**Program elements in TensorFLow**:
TF programme works into two basic components, *viz*., building computational graph and executing a computational graph

types of variables:
1. constants: `W = tf.constant()`
2. variable: `b = tf.Variable([-3], dtype=tf.float32)`
3. placeholder: `x = tf.placeholder(tf.float32)`

`linear_model = W * x + b`


placeholders allow us to feed data to Tf model from outside of a model. It permits value to be assisted later.

`
with tf.Session() as sess:
      result = sess.run(b, feed_dict=(a:3.0))
      
print(result)
`

A session is run to evaluate nodes. This is called as the TF runtime. The following example demonstrate code for running a computation graph

`
a = tf.constant(5.0)
b = tf.constant(3.0)
c = a * b

##### Launch Session
sess = tf.Session()

##### Evaluate the tensor c
print(sess.run(c))`






In [0]:
import tensorflow as tf

In [0]:
zero = tf.Variable(0)

one = tf.constant(1)

new_value = tf.add(zero, one)

update = tf.assign(zero, new_value)

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
init_op = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init_op)

In [0]:
print(sess.run(zero))

0


In [0]:
for _ in range(0,5,1):
  sess.run(update)
  print(sess.run(zero))

1
2
3
4
5


In [0]:
# String operations
hello = tf.constant('hello')
world = tf.constant('world')
helloworld = tf.add(hello, world)

In [0]:
print(sess.run(helloworld))

b'helloworld'


In [0]:
a = tf.placeholder(tf.float32)

In [0]:
b = a * 2

In [0]:
result = sess.run(b, feed_dict={a:3})

print(result)

6.0


In [0]:
result = sess.run(b, feed_dict={a:[2,4,6]})

print(result)

[ 4.  8. 12.]


In [0]:
dictionary = {a:[[[1, 2, 3],[4, 5, 6], [7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]}

result = sess.run(b, feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [0]:
sess.close()

In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)
  print(result)

b'helloworld'


In [0]:
graph = tf.get_default_graph()


In [0]:
graph.get_operations()

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'add_3' type=Add>,
 <tf.Operation 'a' type=Const>]

In [0]:
a = tf.constant(10, name="a")

In [0]:
operations = graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'add_3' type=Add>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'a_1' type=Const>]

In [0]:
b = tf.constant(20, name='b')
operations = graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'add_3' type=Add>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'a_1' type=Const>,
 <tf.Operation 'b' type=Const>]

In [0]:
c = tf.add(a, b, name='c')
c

<tf.Tensor 'c:0' shape=() dtype=int32>

In [0]:
operations = graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'add_3' type=Add>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'a_1' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>]

In [0]:
d = tf.multiply(a, b, name='d')
d

<tf.Tensor 'd:0' shape=() dtype=int32>

In [0]:
operations.append(d)

In [0]:
operations = graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'add_3' type=Add>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'a_1' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'c' type=Add>,
 <tf.Operation 'd' type=Mul>]

In [0]:
sess = tf.Session()
print(sess.run(d))
for op in graph.get_operations():
  print(op.name)

200
Variable/initial_value
Variable
Variable/Assign
Variable/read
Const
Add
Assign
init
Const_1
Const_2
Add_1
Placeholder
mul/y
mul
add_2
add_3
a
a_1
b
c
d


In [0]:
sess.close()

In [0]:
tf.reset_default_graph()

### Use case implementation using TensorFlow:

Lets use various features of an individual to predict what class of income they may belong to (>50K or <=50K) using a census data.

In [0]:
import pandas as pd

In [0]:
!pip install wget

  Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget


In [0]:
import wget

In [0]:
file = wget.download(url='https://raw.githubusercontent.com/agupta98/Tensorflow/master/census_data.csv', out='./census.csv')

In [0]:
!pwd

/content


In [0]:
census = pd.read_csv('census.csv')

In [0]:
census.head()

age          workclass   education  education_num       marital_status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   
2   38            Private     HS-grad              9             Divorced   
3   53            Private        11th              7   Married-civ-spouse   
4   28            Private   Bachelors             13   Married-civ-spouse   

           occupation    relationship    race   gender  capital_gain  \
0        Adm-clerical   Not-in-family   White     Male          2174   
1     Exec-managerial         Husband   White     Male             0   
2   Handlers-cleaners   Not-in-family   White     Male             0   
3   Handlers-cleaners         Husband   Black     Male             0   
4      Prof-specialty            Wife   Black   Female             0   

   capital_loss  hours_per_week  native_country income_bracket  
0             0              40   United-States          <=50K  
1             0              13   United-States          <=50K  
2             0              40   United-States          <=50K  
3             0              40   United-States          <=50K  
4             0              40            Cuba          <=50K

In [0]:
census['income_bracket'].unique()

array([' <=50K', ' >50K'], dtype=object)

In [0]:
def label_fix(label):
  if label == '<=50K':
    return 0
  else:
    return 1

In [0]:
census['income_bracket'] = census['income_bracket'].apply(label_fix)

#### Performing train, test split on census data

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X = census.drop(labels=['income_bracket'], axis=1, inplace=False)
y = census['income_bracket']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

TensorFlow offers an API called estimator

`model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

model.train(input_func, steps=5000)`

prepare feature columns and input function

In [0]:
census.columns

Index(['age', 'workclass', 'education', 'education_num', 'marital_status',
       'occupation', 'relationship', 'race', 'gender', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'income_bracket'],
      dtype='object')

using `feature_columns` for categorical values; use vocabulary  list or just hash buckets

In [0]:
gender = tf.feature_column.categorical_column_with_vocabulary_list("gender", ['Female', 'Male'])
occupation = tf.feature_column.categorical_column_with_hash_bucket("occupation", hash_bucket_size=1000)
marital_status = tf.feature_column.categorical_column_with_hash_bucket("marital_status", hash_bucket_size=1000)
relationship = tf.feature_column.categorical_column_with_hash_bucket("relationship", hash_bucket_size=1000)
education = tf.feature_column.categorical_column_with_hash_bucket("education", hash_bucket_size=1000)
workclass = tf.feature_column.categorical_column_with_hash_bucket("workclass", hash_bucket_size=1000)


create continuous feature_columns for the continuous values using numeric_column

In [0]:
age = tf.feature_column.numeric_column("age")
education_num = tf.feature_column.numeric_column("education_num")
capital_gain = tf.feature_column.numeric_column("capital_gain")
capital_loss = tf.feature_column.numeric_column("capital_loss")
hours_per_week = tf.feature_column.numeric_column("hours_per_week")


Put all these variables into a single list with the variable name feat_cols

In [0]:
feat_cols = [gender, occupation, marital_status, relationship, education, workclass, age, education_num, capital_gain, capital_loss, hours_per_week]

##### Create the input function
batch size is up to you

In [0]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=100, num_epochs=None, shuffle=True)

In [0]:
model = tf.estimator.LinearClassifier(feature_columns=feat_cols)

model.train(input_fn=input_func, steps=5000)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpb0_jlozu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7ff39b556c18>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, u

#### Evaluation

In [0]:
pred_fn = tf.estimator.inputs.pandas_input_fn(x=X_test, batch_size=len(X_test), shuffle=False)

In [0]:
predictions = list(model.predict(input_fn=pred_fn))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /tmp/tmpb0_jlozu/model.ckpt-5000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [0]:
predictions[0]

{'class_ids': array([1]),
 'classes': array([b'1'], dtype=object),
 'logistic': array([1.], dtype=float32),
 'logits': array([21.518827], dtype=float32),
 'probabilities': array([4.513277e-10, 1.000000e+00], dtype=float32)}

Create a list of only class_ids key values from the prediction list of dictionaries, there are predictions you will use to compare against the real y_test values.

In [0]:
final_preds = []
for pred in predictions:
  final_preds.append(pred['class_ids'][0])

In [0]:
from sklearn.metrics import classification_report

In [0]:
print(classification_report(y_test, final_preds))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      9769

   micro avg       1.00      1.00      1.00      9769
   macro avg       1.00      1.00      1.00      9769
weighted avg       1.00      1.00      1.00      9769

